version: '3.9'

services:
  frappe:
    image: erpnext
    container_name: frappe
    restart: always
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - apps:/home/frappe/frappe-bench/apps
    ports:
      - "8004:8000"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frappe.rule=Host(`waves-skipper.com`)"
      - "traefik.http.services.frappe.loadbalancer.server.port=8004"
    environment:
      BACKEND: frappe:8000
      FRAPPE_SITE_NAME_HEADER: $$host
      SOCKETIO: frappe:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"

  configurator:
    image: erpnext
    restart: "no"
    entrypoint:
      - bash
      - -c
    command:
      - >
        bench set-config -g db_host $$DB_HOST;
        bench set-config -g db_port $$DB_PORT;
        bench set-config -g socketio_port $$SOCKETIO_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO";
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      SOCKETIO_PORT: "9000"
      REDIS_CACHE: 127.0.0.1:12000
      REDIS_QUEUE: 127.0.0.1:11000
      REDIS_SOCKETIO: 127.0.0.1:13000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      
  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 15
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  sites:
  apps: