version: "3"

services:
  backend:
    image: worker:latest
    restart: always
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
      - apps:/home/frappe/frappe-bench/apps
      - env:/home/frappe/frappe-bench/env
      - logs:/home/frappe/frappe-bench/logs

  configurator:
    image: worker:latest
    entrypoint:
      - bash
      - -c
    command:
      - >
        bench set-config -g db_host $$DB_HOST;
        bench set-config -g db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO";
        bench set-config -g socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
      - apps:/home/frappe/frappe-bench/apps
      - env:/home/frappe/frappe-bench/env
      - logs:/home/frappe/frappe-bench/logs
    restart: "no"

  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 15
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: worker:latest
    command:
      - nginx-entrypoint.sh
    restart: always
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: $$host
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
      - apps:/home/frappe/frappe-bench/apps
      - env:/home/frappe/frappe-bench/env
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8080:8080"

  queue-default:
    image: worker:latest
    restart: always
    command:
      - bench
      - worker
      - --queue
      - default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
      - apps:/home/frappe/frappe-bench/apps
      - env:/home/frappe/frappe-bench/env
      - logs:/home/frappe/frappe-bench/logs

  queue-long:
    image: worker:latest
    restart: always
    command:
      - bench
      - worker
      - --queue
      - long
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
      - apps:/home/frappe/frappe-bench/apps
      - env:/home/frappe/frappe-bench/env
      - logs:/home/frappe/frappe-bench/logs

  queue-short:
    image: worker:latest
    restart: always
    command:
      - bench
      - worker
      - --queue
      - short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
      - apps:/home/frappe/frappe-bench/apps
      - env:/home/frappe/frappe-bench/env
      - logs:/home/frappe/frappe-bench/logs

  redis-queue:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis-cache-data:/data

  redis-socketio:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis-socketio-data:/data

  scheduler:
    image: worker:latest
    restart: always
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
      - apps:/home/frappe/frappe-bench/apps
      - env:/home/frappe/frappe-bench/env
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: worker:latest
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    restart: always
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
      - apps:/home/frappe/frappe-bench/apps
      - env:/home/frappe/frappe-bench/env
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  redis-queue-data:
  redis-cache-data:
  redis-socketio-data:
  sites:
  assets:
  apps:
  env:
  logs:
