name: Publish Helm Chart
on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - cr.yaml
      - .github/workflows/publish_helm.yaml

jobs:
  build:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add Helm Repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: charts
          config: cr.yaml
          charts_repo_url: https://frappe-containers.castlecraft.in
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
